# Site settings
site: Ephesus
title: Ephesus - Minimalist Jekyll Theme
keywords: ephesus, blog
description: >-
  Ephesus - Minimalist Jekyll Theme
lang: en-US
timezone:  America/Los_Angeles
repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  rajashekr

# Author settings
author:
  name: Rajashekar Chintalapati 
  bio: Software Engineer 
  picture: assets/images/profile.jpg 
  github: rajashekar # github username
  twitter: rajashekar # twitter username
  linkedin: rajashekar-chintalapati # linkedin username
  email: rajshekar.ch@gmail.com # email adress


# URL settings
url: "https://rajashekar.vercel.app" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-toc
  - jekyll-spaceship

paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false